### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by richardolsen** [imurchie/super-reads#1]
Hey, I got this running at https://super-reads.herokuapp.com I can't see a way to add users, books or authors. There was some problems with the seed but I assume these features were never done. The readme seems to suggest/hint these features are done. I'm not up with ruby on rails, nor an backbone, so without these features I'll look elsewhere. Hope this doesn't read as a criticism, as it isn't meant to be. I had to fork and make minor edits to the gem file in order to get this running on heroku. Cheers.

**Comment by imurchie** [comment]
Thanks. To be perfectly honest, I haven't looked at or thought about this in years. And I cannot remember what was implemented and what was not. I have no plans on doing anything with this, so anything that is needed will probably never get done. At least not by me.
